---
  # The name property is used to give a quick description of the task.
  # It is displayed when the task is run during 'vagrant up'.
  # The next line after the name property is the Ansible module that will be
  # used. The properties below that line (indented) are properties of that
  # specific module.
  # Techncially, a lot--if not all--of these commands can be done via bash 
  # commands using the command module (http://docs.ansible.com/command_module.html).


  # Currently setting up ansible to run all of these tasks on all machines. 
  # Hosts can be edited to include only certain machines/IP addresses/groups.
  # 'all' can and should be edited later.
- hosts: all

  tasks:
    # This task will update everything before moving on.
    # I think update_cache can technically be run as a part of
    # the other steps, but it seems helpful to run this at the beginning.
    - name: updating apt cache
      apt: update_cache=yes
      become: yes
      become_method: sudo
    # Need to install this in order to add the java repository
    - name: adding python-software-properties 
      apt: name=python-software-properties
      become: yes
      become_method: sudo
    # Adds the java repository
    - name: adding java repository
      apt_repository: repo='ppa:webupd8team/java'
      become: yes
      become_method: sudo
    # This step takes care of the config menu that pops up when installing
    # Java. Without this step, Ansible gets hung up and isn't able to install Java.
    - name: automatically select the Oracle License - 
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
      become: yes
      become_method: sudo
    # Actually installing java 8
    - name: installing java8
      apt: name=oracle-java8-installer
      become: yes
      become_method: sudo
    # Using the get_url module to download solr5.1.0. Serves the same function as
    # wget or curl.
    - name: get solr5.1.0
      get_url: 
        url: "http://apache.spinellicreations.com/lucene/solr/5.1.0/solr-5.1.0.tgz"
        dest: "/home/vagrant/solr-5.1.0.tgz"
      become: yes
      become_method: sudo
    # This module will unarchive solr
    - name: unzip solr
      unarchive:
        src: "/home/vagrant/solr-5.1.0.tgz"
        dest: "/home/vagrant/"
        copy: no

    # using a bash script supplied by solr to install solar instances as services 
    # (ex: able to check status using "sudo service solr status")
    # this is the preferred method for production
    - name: set up solr node on port 8983
      command: sudo bash /home/vagrant/solr-5.1.0/bin/install_solr_service.sh /home/vagrant/solr-5.1.0.tgz -s solr -p 8983 -u vagrant
      become: yes
      become_method: sudo
    # solr2 node on port 8984
    - name: set up second node on port 8984
      command: sudo bash /home/vagrant/solr-5.1.0/bin/install_solr_service.sh /home/vagrant/solr-5.1.0.tgz -s solr2 -p 8984 -u vagrant
      become: yes
      become_method: sudo
    # solr3 node on port 8985
    - name: set up third node on port 8985
      command: sudo bash /home/vagrant/solr-5.1.0/bin/install_solr_service.sh /home/vagrant/solr-5.1.0.tgz -s solr3 -p 8985 -u vagrant
      become: yes
      become_method: sudo

    # creating cores for all 3 nodes - should not be done in sudo or else files
    # will be owned by root (but need to be run by vagrant)
    - name: set up core1 on node 1 (port 8983)
      command: /home/vagrant/solr-5.1.0/bin/solr create -c core1 -p 8983
    - name: set up core1 on node 2 (port 8984)
      command: /home/vagrant/solr-5.1.0/bin/solr create -c core1 -p 8984
    - name: set up core1 on node 3 (port 8985)
      command: /home/vagrant/solr-5.1.0/bin/solr create -c core1 -p 8985
